# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hiha/c++/Camera

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hiha/c++/Camera

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hiha/c++/Camera/CMakeFiles /home/hiha/c++/Camera//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hiha/c++/Camera/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named CameraCalibration

# Build rule for target.
CameraCalibration: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CameraCalibration
.PHONY : CameraCalibration

# fast build rule for target.
CameraCalibration/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CameraCalibration.dir/build.make CMakeFiles/CameraCalibration.dir/build
.PHONY : CameraCalibration/fast

#=============================================================================
# Target rules for targets named CameraPosition

# Build rule for target.
CameraPosition: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CameraPosition
.PHONY : CameraPosition

# fast build rule for target.
CameraPosition/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CameraPosition.dir/build.make CMakeFiles/CameraPosition.dir/build
.PHONY : CameraPosition/fast

#=============================================================================
# Target rules for targets named webcamTracking

# Build rule for target.
webcamTracking: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 webcamTracking
.PHONY : webcamTracking

# fast build rule for target.
webcamTracking/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webcamTracking.dir/build.make CMakeFiles/webcamTracking.dir/build
.PHONY : webcamTracking/fast

#=============================================================================
# Target rules for targets named tcp_client

# Build rule for target.
tcp_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tcp_client
.PHONY : tcp_client

# fast build rule for target.
tcp_client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_client.dir/build.make CMakeFiles/tcp_client.dir/build
.PHONY : tcp_client/fast

CameraCalibration.o: CameraCalibration.cpp.o
.PHONY : CameraCalibration.o

# target to build an object file
CameraCalibration.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CameraCalibration.dir/build.make CMakeFiles/CameraCalibration.dir/CameraCalibration.cpp.o
.PHONY : CameraCalibration.cpp.o

CameraCalibration.i: CameraCalibration.cpp.i
.PHONY : CameraCalibration.i

# target to preprocess a source file
CameraCalibration.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CameraCalibration.dir/build.make CMakeFiles/CameraCalibration.dir/CameraCalibration.cpp.i
.PHONY : CameraCalibration.cpp.i

CameraCalibration.s: CameraCalibration.cpp.s
.PHONY : CameraCalibration.s

# target to generate assembly for a file
CameraCalibration.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CameraCalibration.dir/build.make CMakeFiles/CameraCalibration.dir/CameraCalibration.cpp.s
.PHONY : CameraCalibration.cpp.s

CameraPosition.o: CameraPosition.cpp.o
.PHONY : CameraPosition.o

# target to build an object file
CameraPosition.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CameraPosition.dir/build.make CMakeFiles/CameraPosition.dir/CameraPosition.cpp.o
.PHONY : CameraPosition.cpp.o

CameraPosition.i: CameraPosition.cpp.i
.PHONY : CameraPosition.i

# target to preprocess a source file
CameraPosition.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CameraPosition.dir/build.make CMakeFiles/CameraPosition.dir/CameraPosition.cpp.i
.PHONY : CameraPosition.cpp.i

CameraPosition.s: CameraPosition.cpp.s
.PHONY : CameraPosition.s

# target to generate assembly for a file
CameraPosition.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CameraPosition.dir/build.make CMakeFiles/CameraPosition.dir/CameraPosition.cpp.s
.PHONY : CameraPosition.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

tcp_client.o: tcp_client.cpp.o
.PHONY : tcp_client.o

# target to build an object file
tcp_client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_client.dir/build.make CMakeFiles/tcp_client.dir/tcp_client.cpp.o
.PHONY : tcp_client.cpp.o

tcp_client.i: tcp_client.cpp.i
.PHONY : tcp_client.i

# target to preprocess a source file
tcp_client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_client.dir/build.make CMakeFiles/tcp_client.dir/tcp_client.cpp.i
.PHONY : tcp_client.cpp.i

tcp_client.s: tcp_client.cpp.s
.PHONY : tcp_client.s

# target to generate assembly for a file
tcp_client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_client.dir/build.make CMakeFiles/tcp_client.dir/tcp_client.cpp.s
.PHONY : tcp_client.cpp.s

webcamTracking.o: webcamTracking.cpp.o
.PHONY : webcamTracking.o

# target to build an object file
webcamTracking.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webcamTracking.dir/build.make CMakeFiles/webcamTracking.dir/webcamTracking.cpp.o
.PHONY : webcamTracking.cpp.o

webcamTracking.i: webcamTracking.cpp.i
.PHONY : webcamTracking.i

# target to preprocess a source file
webcamTracking.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webcamTracking.dir/build.make CMakeFiles/webcamTracking.dir/webcamTracking.cpp.i
.PHONY : webcamTracking.cpp.i

webcamTracking.s: webcamTracking.cpp.s
.PHONY : webcamTracking.s

# target to generate assembly for a file
webcamTracking.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webcamTracking.dir/build.make CMakeFiles/webcamTracking.dir/webcamTracking.cpp.s
.PHONY : webcamTracking.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CameraCalibration"
	@echo "... CameraPosition"
	@echo "... main"
	@echo "... tcp_client"
	@echo "... webcamTracking"
	@echo "... CameraCalibration.o"
	@echo "... CameraCalibration.i"
	@echo "... CameraCalibration.s"
	@echo "... CameraPosition.o"
	@echo "... CameraPosition.i"
	@echo "... CameraPosition.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... tcp_client.o"
	@echo "... tcp_client.i"
	@echo "... tcp_client.s"
	@echo "... webcamTracking.o"
	@echo "... webcamTracking.i"
	@echo "... webcamTracking.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

